Repository wildcodeschool-2025-03/straszik, pull requests merged in 2025-05, with the labels that each got.

#24 US11_Newsletter
  client/public/maison-musicien.png
  client/public/yavuz-kutuk.jpeg
  client/public/yavuz-kutuk.png
  client/src/components/Backstage/InstrumentCard.tsx
  client/src/components/CardAccount/CardAccount.tsx
  client/src/components/Footer/Footer.tsx
  client/src/pages/Contact/Contact.tsx
  client/src/pages/Evenements/Evenements.tsx
Labels: Add_Features

#27 Us15 ter add features bastket
  client/src/components/Header/Header.tsx
  client/src/pages/Basket/Basket.tsx
  client/src/pages/Boutique/Boutique.tsx
  package-lock.json
Labels: bug, Add_Features

#28 US14_AdminConnexion
  client/public/yavuz-kutuk.png
  client/src/components/Header/Header.tsx
  client/src/components/LogInAccount/LogInAccount.tsx
  client/src/data/adminAccounts.json
  client/src/main.tsx
  client/src/pages/Accueil/Accueil.tsx
  client/src/pages/Admin/Admin.tsx
Labels: Add_Features

#34 US_19_Admin_page - fonctionnalités ok
  client/package.json
  client/src/components/Footer/Footer.tsx
  client/src/components/NewsletterList/NewsletterList.tsx
  client/src/components/UserList/UserList.tsx
  client/src/pages/Admin/Admin.tsx
  package-lock.json
Labels: Add_Features

#35 US20_Bis_AddFeaturestoBasket
  client/src/components/CardAccount/CardAccount.tsx
  client/src/components/ui/Button.tsx
  client/src/components/ui/Dialog.tsx
  client/src/pages/Basket/Basket.tsx
  package-lock.json
Labels: Add_Features

#36 Fix admin
  client/src/components/CardAccount/CardAccount.tsx
  client/src/components/Footer/Footer.tsx
  client/src/components/NewsletterList/NewsletterList.tsx
  client/src/components/UserList/UserList.tsx
  client/src/pages/Basket/Basket.tsx
Labels: Fix

#40 Fix_CardAccount_Mdp
  client/src/components/CardAccount/CardAccount.tsx
  client/src/main.tsx
  client/src/pages/Admin/Admin.tsx
Labels: Fix
