Repository wildcodeschool-2025-03/straszik, pull requests merged in 2025-04, with the labels that each got.

#1 US_06_Structure
  client/index.html
  client/package.json
  client/src/App.css
  client/src/App.tsx
  client/src/main.tsx
  client/src/pages/Accueil/Accueil.tsx
  client/src/pages/Backstage/Backstage.tsx
  client/src/pages/Boutique/Boutique.tsx
  client/src/pages/Compte/Compte.tsx
  client/src/pages/Contact/Contact.tsx
  client/src/pages/Discographie/Discographie.tsx
  client/src/pages/Evenements/Evenements.tsx
  client/src/pages/Log/Log.tsx
  client/src/pages/Rockband/Rockband.tsx
  client/vite.config.ts
  package-lock.json
Labels: enhancement

#4 US_06_bis_header
  client/package.json
  client/src/App.css
  client/src/App.tsx
  client/src/assets/images/account_circle.png
  client/src/assets/images/background.png
  client/src/assets/images/background.webp
  client/src/assets/images/logo.png
  client/src/components/Header/Header.tsx
  client/src/pages/Accueil/Accueil.tsx
Labels: Add_Features

#6 US03_Add_Goodies
  client/public/vinyle.png
  client/src/App.css
  client/src/components/Footer/Footer.tsx
  client/src/components/Header/Header.tsx
  client/src/pages/Boutique/Boutique.tsx
  server/bin/seed.ts
Labels: Add_Features

#8 US_01_RockBand - Add RockBand
  client/index.html
  client/public/Alexandra.png
  client/public/Eric.png
  client/public/Maxime.png
  client/public/Quentin.png
  client/src/App.css
  client/src/App.tsx
  client/src/components/GroupeImg/GroupeImg.tsx
  client/src/components/GrpPresentation/GrpPresentation.tsx
  client/src/components/Header/Header.tsx
  client/src/pages/Rockband/Rockband.tsx
Labels: Add_Features

#7 US04_eventsComponent
  client/index.html
  client/src/pages/Evenements/Evenements.tsx
Labels: question, Add_Features

#9 US_02_Discographie
  client/index.html
  client/src/App.css
  client/src/assets/images/logo.ico
  client/src/components/Discographie/AlbumDetails.tsx
  client/src/components/Discographie/AlbumPochette.tsx
  client/src/components/Footer/Footer.tsx
  client/src/components/Header/Header.tsx
  client/src/pages/Discographie/Discographie.tsx
Labels: question, Add_Features

#11 Add_Backstage
  client/public/bass.png
  client/public/batterie.png
  client/public/carnet-notes.png
  client/public/dedicace.png
  client/public/guitare.png
  client/public/loge-maquillage.png
  client/public/micro.png
  client/public/route.png
  client/public/scene.png
  client/public/studio.png
  client/src/App.css
  client/src/components/Backstage/InstrumentCard.tsx
  client/src/components/Backstage/ZoomImage.tsx
  client/src/components/Footer/Footer.tsx
  client/src/components/GroupeImg/GroupeImg.tsx
  client/src/pages/Backstage/Backstage.tsx
  client/src/pages/Boutique/Boutique.tsx
  package-lock.json
Labels: Add_Features

#12 Us 17 mon compte fix
  client/package.json
  client/src/App.css
  client/src/components/CardAccount/CardAccount.tsx
  client/src/components/Footer/Footer.tsx
  client/src/main.tsx
  client/src/pages/Compte/Compte.tsx
  package-lock.json
Labels: Fix, Add_Features

#16 Add US01_HomePage+Features
  client/src/assets/images/vinyle.png
  client/src/components/AlbumHome/AlbumHome.tsx
  client/src/components/AudioPlayer/AudioPlayer.tsx
  client/src/components/EventsHome/EventsHome.tsx
  client/src/components/GoodiesHome/GoodiesHome.tsx
  client/src/components/PhotoHotspots/PhotoHotspots.tsx
  client/src/pages/Accueil/Accueil.tsx
Labels: Add_Features

#15 Us 15 log in
  client/src/App.css
  client/src/components/Header/Header.tsx
  client/src/components/LogInAccount/LogInAccount.tsx
  client/src/main.tsx
  client/src/pages/Boutique/Boutique.tsx
  client/src/pages/Log/Log.tsx
Labels: bug, Add_Features

#17 Fix package
  client/package.json
  client/src/components/PhotoHotspots/PhotoHotspots.tsx
  package-lock.json
Labels: Fix

#19 Fix_ColorBlock
  client/src/App.css
Labels: Fix

#20 fix_img_sourc_vercel
  client/public/account_circle.png
  client/public/background.png
  client/public/copyright-icon.png
  client/public/facebook-icon.png
  client/public/instagram-icon.png
  client/public/logo.ico
  client/public/logo.png
  client/public/photogroupe.png
  client/src/App.css
  client/src/assets/images/vinyle.png
  client/src/components/AudioPlayer/AudioPlayer.tsx
  client/src/components/Footer/Footer.tsx
  client/src/components/Header/Header.tsx
  client/src/pages/Accueil/Accueil.tsx
  client/src/pages/Backstage/Backstage.tsx
Labels: Fix

#21 Fix design
  client/public/yavuz-kutuk.jpeg
  client/src/components/Backstage/InstrumentCard.tsx
  client/src/components/CardAccount/CardAccount.tsx
  client/src/components/Discographie/AlbumDetails.tsx
  client/src/components/Discographie/AlbumPochette.tsx
  client/src/components/GroupeImg/GroupeImg.tsx
  client/src/components/GrpPresentation/GrpPresentation.tsx
  client/src/components/Header/Header.tsx
  client/src/components/LogInAccount/LogInAccount.tsx
  client/src/pages/Backstage/Backstage.tsx
  client/src/pages/Boutique/Boutique.tsx
  client/src/pages/Contact/Contact.tsx
  client/src/pages/Discographie/Discographie.tsx
  client/src/pages/Evenements/Evenements.tsx
Labels: bug, Fix

#22 US_17Bis_Inscription
  client/index.html
  client/src/App.tsx
  client/src/components/CardAccount/CardAccount.tsx
  client/src/components/Header/Header.tsx
  client/src/components/LogInAccount/LogInAccount.tsx
  client/src/components/PhotoHotspots/PhotoHotspots.tsx
  client/src/components/SignIn/SignIn.tsx
  client/src/main.tsx
  client/src/pages/Accueil/Accueil.tsx
  client/src/pages/Compte/Compte.tsx
  client/src/pages/Inscription/Inscription.tsx
  client/src/pages/Sign/Sign.tsx
Labels: Add_Features

#23 US_15Bis_Panier
  client/src/App.tsx
  client/src/Context/BasketContext.tsx
  client/src/components/GroupeImg/GroupeImg.tsx
  client/src/components/Header/Header.tsx
  client/src/main.tsx
  client/src/pages/Accueil/Accueil.tsx
  client/src/pages/Basket/Basket.tsx
  client/src/pages/Boutique/Boutique.tsx
Labels: invalid, Add_Features
